const exp = [
  {
    date: '2024-09-01',
    title: 'Lunch at Cafe',
    desc: 'Group lunch with colleagues',
    isSettled: false,
    group: 'Work Colleagues',
    amount: 50.0,
    to: 'John',
    from: 'Alice',
  },
  {
    date: '2024-09-03',
    title: 'Movie Tickets',
    desc: 'Watched a movie with friends',
    isSettled: true,
    group: 'Friends',
    amount: 30.0,
    to: 'David',
    from: 'Emily',
  },
  {
    date: '2024-09-05',
    title: 'Groceries',
    desc: 'Shared groceries for home',
    isSettled: false,
    group: 'Roommates',
    amount: 80.0,
    to: 'Michael',
    from: 'Sarah',
  },
  {
    date: '2024-09-07',
    title: 'Concert Tickets',
    desc: 'Tickets for a concert',
    isSettled: true,
    group: 'Music Lovers',
    amount: 120.0,
    to: 'Anna',
    from: 'Mark',
  },
  {
    date: '2024-09-09',
    title: 'Dinner Outing',
    desc: 'Family dinner at a restaurant',
    isSettled: false,
    group: 'Family',
    amount: 100.0,
    to: 'Sophia',
    from: 'Olivia',
  },
];
export default exp;
